export interface PresetTopic {
  title: string
  description: string
  domain: string
  difficulty: string
  xpReward: number
}

export interface PresetPath {
  id: string
  name: string
  icon: string
  description: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  tags: string[]
  topics: PresetTopic[]
}

export const PRESET_PATHS: PresetPath[] = [
  {
    id: 'web-hacker',
    name: 'Web Hacker',
    icon: '🌐',
    description: 'Master web application security from HTTP basics to advanced bug bounty techniques.',
    difficulty: 'intermediate',
    tags: ['Bug Bounty', 'OWASP', 'Pentest'],
    topics: [
      {
        title: 'HTTP Fundamentals',
        description: 'Understand HTTP/HTTPS protocol, headers, cookies, sessions, and how web traffic flows.',
        domain: 'web',
        difficulty: 'beginner',
        xpReward: 50,
      },
      {
        title: 'OWASP Top 10',
        description: 'Learn the 10 most critical web application security risks including injection, broken auth, and more.',
        domain: 'web',
        difficulty: 'beginner',
        xpReward: 75,
      },
      {
        title: 'Cross-Site Scripting (XSS)',
        description: 'Understand reflected, stored, and DOM-based XSS attacks, bypass techniques, and mitigations.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'SQL Injection',
        description: 'Master classic, blind, and time-based SQLi. Practice with UNION-based extraction and error-based attacks.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Cross-Site Request Forgery (CSRF)',
        description: 'Learn CSRF attack patterns, bypass same-site cookies, and effective CSRF token implementation.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 75,
      },
      {
        title: 'Server-Side Request Forgery (SSRF)',
        description: 'Explore SSRF to reach internal services, cloud metadata endpoints, and bypass filter techniques.',
        domain: 'web',
        difficulty: 'advanced',
        xpReward: 125,
      },
      {
        title: 'Authentication Attacks',
        description: 'Study JWT vulnerabilities, OAuth misconfigurations, password spray, and multi-factor bypass.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'API Security',
        description: 'Test REST and GraphQL APIs for BOLA, excessive data exposure, mass assignment, and rate limit flaws.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Burp Suite Mastery',
        description: 'Use Burp Suite for intercepting, modifying requests, scanning, Intruder, Repeater, and extensions.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 125,
      },
      {
        title: 'Bug Bounty Methodology',
        description: 'Build a systematic approach: scope review, recon, testing phases, POC writing, and responsible disclosure.',
        domain: 'web',
        difficulty: 'advanced',
        xpReward: 150,
      },
    ],
  },
  {
    id: 'network-defender',
    name: 'Network Defender',
    icon: '🛡️',
    description: 'Build robust network defenses from subnetting to zero trust architecture.',
    difficulty: 'intermediate',
    tags: ['Blue Team', 'Firewall', 'Zero Trust'],
    topics: [
      {
        title: 'Networking Fundamentals',
        description: 'OSI model, network devices, LAN/WAN, switching, routing basics, and network topologies.',
        domain: 'networking',
        difficulty: 'beginner',
        xpReward: 50,
      },
      {
        title: 'Subnetting & CIDR',
        description: 'Master IP addressing, CIDR notation, subnetting calculations, and VLSM design.',
        domain: 'networking',
        difficulty: 'beginner',
        xpReward: 75,
      },
      {
        title: 'TCP/IP Deep Dive',
        description: 'Understand TCP handshake, flags, state machine, UDP, ICMP, and common protocol attacks.',
        domain: 'networking',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Firewalls & ACLs',
        description: 'Configure stateful firewalls, write ACL rules, understand packet filtering vs application layer firewalls.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'IDS/IPS Systems',
        description: 'Deploy Snort/Suricata, write detection rules, tune signatures, and handle false positives.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'VPN & Tunneling',
        description: 'Understand IPSec, OpenVPN, WireGuard, SSL VPNs, and secure tunneling protocols.',
        domain: 'networking',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Packet Analysis with Wireshark',
        description: 'Capture and analyze network traffic, identify anomalies, extract artifacts, and filter effectively.',
        domain: 'networking',
        difficulty: 'intermediate',
        xpReward: 125,
      },
      {
        title: 'DNS Security',
        description: 'Understand DNS attacks (poisoning, amplification, tunneling), DNSSEC, and DNS filtering.',
        domain: 'networking',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Network Forensics',
        description: 'Reconstruct incidents from PCAP files, identify malware C2, lateral movement, and data exfiltration.',
        domain: 'defense',
        difficulty: 'advanced',
        xpReward: 150,
      },
      {
        title: 'Zero Trust Architecture',
        description: 'Design zero trust networks with micro-segmentation, identity verification, and least-privilege access.',
        domain: 'defense',
        difficulty: 'advanced',
        xpReward: 150,
      },
    ],
  },
  {
    id: 'soc-analyst',
    name: 'SOC Analyst',
    icon: '🔍',
    description: 'Become a Security Operations Center analyst — from log analysis to threat hunting.',
    difficulty: 'intermediate',
    tags: ['Blue Team', 'SIEM', 'Incident Response'],
    topics: [
      {
        title: 'Log Analysis Fundamentals',
        description: 'Parse and interpret system logs, web server logs, authentication logs, and security events.',
        domain: 'defense',
        difficulty: 'beginner',
        xpReward: 50,
      },
      {
        title: 'SIEM Fundamentals',
        description: 'Understand SIEM architecture, data ingestion, correlation rules, dashboards, and alerting.',
        domain: 'defense',
        difficulty: 'beginner',
        xpReward: 75,
      },
      {
        title: 'Incident Response Process',
        description: 'Master the IR lifecycle: preparation, identification, containment, eradication, recovery, and lessons learned.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Threat Intelligence',
        description: 'Understand IOCs, IOAs, threat feeds, MITRE ATT&CK framework, and intelligence-driven defense.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Malware Analysis Basics',
        description: 'Static and dynamic analysis of malware: strings, PE headers, sandboxing, and behavioral analysis.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 125,
      },
      {
        title: 'Phishing Investigation',
        description: 'Analyze phishing emails, headers, URLs, attachments, and trace campaigns to attribution.',
        domain: 'defense',
        difficulty: 'beginner',
        xpReward: 75,
      },
      {
        title: 'Windows Event Logs',
        description: 'Understand Event IDs for logon, process creation, lateral movement, and PowerShell activity.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Linux Audit Logs',
        description: 'Use auditd, /var/log analysis, and syslog to detect unauthorized access and privilege escalation.',
        domain: 'linux',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Alert Triage & Playbooks',
        description: 'Prioritize alerts, reduce alert fatigue, build and follow playbooks for common attack scenarios.',
        domain: 'defense',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Threat Hunting',
        description: 'Proactive hunting using hypothesis-driven approach, EDR telemetry, and MITRE ATT&CK mapping.',
        domain: 'defense',
        difficulty: 'advanced',
        xpReward: 150,
      },
    ],
  },
  {
    id: 'bug-bounty-hunter',
    name: 'Bug Bounty Hunter',
    icon: '🏆',
    description: 'Go from recon to payout — the complete bug bounty hunting methodology.',
    difficulty: 'intermediate',
    tags: ['Bug Bounty', 'Recon', 'OSINT'],
    topics: [
      {
        title: 'Recon & OSINT',
        description: 'Use Google dorks, Shodan, Censys, LinkedIn, and OSINT frameworks to gather target intelligence.',
        domain: 'recon',
        difficulty: 'beginner',
        xpReward: 75,
      },
      {
        title: 'Subdomain Enumeration',
        description: 'Use amass, subfinder, assetfinder, and DNS brute-forcing to discover attack surface.',
        domain: 'recon',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Web Application Recon',
        description: 'Directory busting, technology fingerprinting, parameter discovery, and endpoint mapping.',
        domain: 'recon',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'OWASP Top 10 for Hunters',
        description: 'Apply OWASP vulnerabilities in a bug bounty context — what pays, what gets duplicated, what gets dismissed.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'API Security Testing',
        description: 'Hunt for BOLA/IDOR in APIs, test GraphQL introspection, find mass assignment and rate limit flaws.',
        domain: 'web',
        difficulty: 'intermediate',
        xpReward: 125,
      },
      {
        title: 'Business Logic Flaws',
        description: 'Find price manipulation, workflow bypass, privilege escalation through application logic errors.',
        domain: 'web',
        difficulty: 'advanced',
        xpReward: 150,
      },
      {
        title: 'Responsible Disclosure',
        description: 'Understand coordinated disclosure, CVE process, security.txt, and working with security teams.',
        domain: 'general',
        difficulty: 'beginner',
        xpReward: 50,
      },
      {
        title: 'Writing Good Bug Reports',
        description: 'Structure a compelling report with clear title, CVSS, reproduction steps, impact, and POC.',
        domain: 'general',
        difficulty: 'beginner',
        xpReward: 75,
      },
      {
        title: 'Program Selection Strategy',
        description: 'Choose the right programs, understand scope, identify high-ROI targets, and manage your pipeline.',
        domain: 'general',
        difficulty: 'intermediate',
        xpReward: 75,
      },
      {
        title: 'Automation & Tooling',
        description: 'Build automation pipelines with nuclei, httpx, gau, waybackurls, and custom scripts.',
        domain: 'recon',
        difficulty: 'advanced',
        xpReward: 150,
      },
    ],
  },
  {
    id: 'oscp-prep',
    name: 'OSCP Prep',
    icon: '💀',
    description: 'Systematic preparation for the Offensive Security Certified Professional exam.',
    difficulty: 'advanced',
    tags: ['OSCP', 'Pentest', 'Exploitation'],
    topics: [
      {
        title: 'Enumeration Methodology',
        description: 'Systematic enumeration: port scanning, service detection, OS fingerprinting, and output organization.',
        domain: 'recon',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Service Fingerprinting',
        description: 'Identify and research services: FTP, SSH, SMB, RPC, HTTP, MSSQL, MySQL, and more.',
        domain: 'networking',
        difficulty: 'intermediate',
        xpReward: 100,
      },
      {
        title: 'Exploitation Basics',
        description: 'Understand buffer overflows, exploit development, using Metasploit and public exploits safely.',
        domain: 'general',
        difficulty: 'advanced',
        xpReward: 150,
      },
      {
        title: 'Password Attacks',
        description: 'Hash cracking with hashcat/john, credential stuffing, pass-the-hash, and password spraying.',
        domain: 'general',
        difficulty: 'intermediate',
        xpReward: 125,
      },
      {
        title: 'Privilege Escalation — Linux',
        description: 'SUID binaries, sudo misconfigs, cron jobs, writable paths, kernel exploits, and capability abuse.',
        domain: 'linux',
        difficulty: 'advanced',
        xpReward: 175,
      },
      {
        title: 'Privilege Escalation — Windows',
        description: 'Unquoted paths, weak services, token impersonation, AlwaysInstallElevated, and registry exploits.',
        domain: 'general',
        difficulty: 'advanced',
        xpReward: 175,
      },
      {
        title: 'Pivoting & Tunneling',
        description: 'SSH tunneling, chisel, sshuttle, proxychains, and network pivoting through compromised hosts.',
        domain: 'networking',
        difficulty: 'advanced',
        xpReward: 175,
      },
      {
        title: 'Active Directory Basics',
        description: 'Understand AD structure, Kerberos, LDAP enumeration, Kerberoasting, and Pass-the-Ticket.',
        domain: 'general',
        difficulty: 'advanced',
        xpReward: 200,
      },
      {
        title: 'Post-Exploitation',
        description: 'Pillaging, persistence mechanisms, covering tracks, credential harvesting, and lateral movement.',
        domain: 'general',
        difficulty: 'advanced',
        xpReward: 175,
      },
      {
        title: 'OSCP Report Writing',
        description: 'Write professional pentest reports: executive summary, technical findings, remediation, and evidence.',
        domain: 'general',
        difficulty: 'intermediate',
        xpReward: 100,
      },
    ],
  },
]
